"""empty message

Revision ID: 319a292a8ad8
Revises: 
Create Date: 2024-04-15 22:11:21.409256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319a292a8ad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('IIN', sa.String(length=12), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('gender', sa.Enum('Мужской', 'Женский', name='genderEnum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.Enum('Pediatrician', 'Gynecologist', 'Psychiatrist', 'Internists', 'Oncologist', 'Dermatologist', name='doctorQualificationEnum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IIN')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('IIN', sa.String(length=12), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('gender', sa.Enum('Мужской', 'Женский', name='genderEnum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('ethnicity', sa.Enum('Азиат', 'Европеец', name='ethnicityEnum'), nullable=False),
    sa.Column('region', sa.String(length=256), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('BMI', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education', sa.Enum('Не оконченное среднее', 'Среднее', 'Высшие', name='educationEnum'), nullable=False),
    sa.Column('marital_status', sa.Enum('Не замужем/не женат', 'За мужем/женат', 'Разведен/вдова/вдовец', name='marital_statusEnum'), nullable=False),
    sa.Column('job_description', sa.Enum('Требующая большой концентрации', 'Офисная', 'Не работаю', 'С активной физ нагрузкой', 'Другое', name='job_descriptionEnum'), nullable=False),
    sa.Column('driving_status', sa.Enum('Да', 'Нет', name='driving_statusEnum'), nullable=False),
    sa.Column('was_involved_in_car_accidents', sa.Enum('Да', 'Нет', name='was_involved_in_car_accidentsEnum'), nullable=False),
    sa.Column('cirrhosis', sa.Enum('ХГС', 'ХГВ', 'ХГД', 'НАЖБП/МАЖБП', 'Алкогольный стеатогепатит', 'Аутоиммунный гепатит', 'ПБХ', 'ПСХ', 'ПБХ + АИГ', 'ПСХ + АИГ', 'БВК', 'Гемохроматоз', 'Другое', 'Нет', name='cirrhosisEnum'), nullable=False),
    sa.Column('duration_of_illness', sa.Integer(), nullable=False),
    sa.Column('platelet_count', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('hemoglobin_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('ALT', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('ALT_upper', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('AAT', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('AAT_upper', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('bilirubin', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('creatinine', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('INA', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('albumin', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sodium_blood_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('potassium_ion', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('blood_ammonia', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('indirect_elastography_of_liver', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('indirect_elastography_of_spleen', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('EVV', sa.Enum('1 степень', '2 степень', '3 степень', '4 степень', 'Нет', name='EVVEnum'), nullable=False),
    sa.Column('red_flags_EVV', sa.Enum('Да', 'Нет', name='red_flags_EVVEnum'), nullable=False),
    sa.Column('presence_of_ascites', sa.Enum('Нет', 'Контролируемый', 'Рефракетерный', name='presence_of_ascitesEnum'), nullable=False),
    sa.Column('reitan_test', sa.Enum('<40 сек', '41-60 сек', '61-90 сек', '91-120 сек', '>120 сек', 'Нет данных', name='reitan_testEnum'), nullable=False),
    sa.Column('view_ents', sa.Enum('АВС', 'Скрытая свная', 'Другое', name='view_entsEnum'), nullable=False),
    sa.Column('comorbidities', sa.String(length=256), nullable=False),
    sa.Column('hepatocellular_carcinoma', sa.Enum('Да', 'Нет', name='hepatocellular_carcinomaEnum'), nullable=False),
    sa.Column('was_hospitalized', sa.Enum('Планово', 'Экстренно', 'Нет', name='was_hospitalizedEnum'), nullable=False),
    sa.Column('was_injured', sa.Enum('Да', 'Нет', name='was_injuredEnum'), nullable=False),
    sa.Column('GIB', sa.Enum('Да', 'Нет', name='GIBEnum'), nullable=False),
    sa.Column('previous_infectious_diseases', sa.Enum('Да', 'Нет', name='previous_infectious_diseasesEnum'), nullable=False),
    sa.Column('stool_character', sa.Enum('Регулярный (1 раз в 1-2 дня)', 'Запор', 'Диарея', name='stool_characterEnum'), nullable=False),
    sa.Column('dehydration', sa.String(length=256), nullable=False),
    sa.Column('portosystemic_bypass_surgery', sa.Enum('Шунтирующие операции', 'Спонтанные шунты', 'Нет', 'Другое', name='portosystemic_bypass_surgeryEnum'), nullable=False),
    sa.Column('thrombosis', sa.Enum('Нет', 'Тромбоз воротной вены', 'Тромбоз печеночных вен', name='thrombosisEnum'), nullable=False),
    sa.Column('medicines', sa.Enum('Прием бензодиазепин', 'Прием опиодов', 'ИПП', 'Другое', name='medicinesEnum'), nullable=False),
    sa.Column('renal_impairment', sa.Enum('Да', 'Нет', name='renal_impairmentEnum'), nullable=False),
    sa.Column('bad_habits', sa.Enum('Табакокурение', 'Злоупотребление алкоголем', 'Нет', 'Другое', name='bad_habitsEnum'), nullable=False),
    sa.Column('CPU', sa.Enum('Имелась', 'Отсутствовала', name='CPUEnum'), nullable=False),
    sa.Column('accepted_PE_medications', sa.String(length=256), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IIN')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
