"""empty message

Revision ID: 8fb6629fc079
Revises: 5b0587f7b408
Create Date: 2024-04-10 10:08:12.169014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb6629fc079'
down_revision: Union[str, None] = '5b0587f7b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'username',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'username',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
